name: Deploy PyPI
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pairplots
    permissions:
      id-token: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.8
      - name: "Install building tools"
        run: pip install build
      - name: "Build package"
        run: python -m build
      - name: "Publish distribution 📦 to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
