name: octtofitterpy backend update
on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:
permissions:
  pull-requests: write
  contents: write
jobs:
  update_compat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: pip

      - name: "Install octtofitterpy"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py install
          # Not needed:
          # python -c 'import pairplots; pairplots.install()'

      - name: "Get PairPlots.jl latest version"
        id: get-latest
        run: |
          cd $(mktemp -d)
          git clone https://github.com/sefffal/PairPlots.jl
          cd PairPlots.jl
          echo "version=$(git describe --tags --abbrev=0 | sed 's/^v//')" >> $GITHUB_OUTPUT
          echo "version=$(git describe --tags --abbrev=0 | sed 's/^v//')"

      - name: "Get PairPlots.jl version used in octtofitterpy"
        # TODO: we can probably just use a REGEX here to avoid having to install the whole julia packages and stack
        id: get-current
        run: |
          python -c 'import pairplots; print(pairplots.version.__pairplots_jl_version__)'
          echo "version=$(python -c 'import pairplots; print(pairplots.version.__pairplots_jl_version__)' 2>/dev/null)" >> $GITHUB_OUTPUT

      # If versions are different, we want to take our checked-out version,
      # create a new branch called "update_compat_{...}", where the "..."
      # is a timestamp. We then want to
      # go to pairplots/version.py, bump the patch version of octtofitterpy (__version__),
      # set the version of __pairplots_jl_version__ to the latest
      # version of PairPlots.jl, and then commit and push.
      # Finally, we will open a PR from this branch to master.
      - name: "Update versions"
        if: ${{ steps.get-latest.outputs.version != steps.get-current.outputs.version }}
        run: |
          # Bump python package patch number
          echo Current pyproject.toml contents
          cat pyproject.toml
          CURRENT_PY_VERSION_NUMBER=$(perl -nle 'print $1 if /version\s*=\s*"(\d+\.\d+)\.\d+"/' pyproject.toml)
          CURRENT_PY_PATCH_NUMBER=$(perl -nle 'print $1 if /version\s*=\s*"\d+\.\d+\.(\d+)"/' pyproject.toml)
          NEW_PY_PATCH_NUMBER=$((CURRENT_PY_PATCH_NUMBER + 1))
          echo CURRENT_PY_VERSION_NUMBER=$CURRENT_PY_VERSION_NUMBER CURRENT_PY_PATCH_NUMBER=$CURRENT_PY_PATCH_NUMBER NEW_PY_PATCH_NUMBER=$NEW_PY_PATCH_NUMBER
          sed -i.bak  "s/version = .*/version = \"$CURRENT_PY_VERSION_NUMBER.$NEW_PY_PATCH_NUMBER\"/" pyproject.toml
          echo Updated pyproject.toml contents
          cat pyproject.toml

          # Set new backend julia package version     
          echo Current pairplots/juliapkg.json contents
          cat pairplots/juliapkg.json
          # Assumes your julia package is the first in the list.
          CURRENT_JL_VERSION_NUMBER=$(perl -nle 'print $1 if /"version"\s*:\s*"(.\d+\.\d+\.\d+)"/' pairplots/juliapkg.json | head -n 1)
          NEW_JL_VERSION_NUMBER="${{ steps.get-latest.outputs.version }}"
          echo CURRENT_JL_VERSION_NUMBER=$CURRENT_JL_VERSION_NUMBER NEW_JL_VERSION_NUMBER=$NEW_JL_VERSION_NUMBER
          sed -i.bak  "s/\"version\": \"$CURRENT_JL_VERSION_NUMBER\"/\"version\": \"=$NEW_JL_VERSION_NUMBER\"/" pairplots/juliapkg.json
          echo Updated pairplots/juliapkg.json contents
          cat pairplots/juliapkg.json

      - name: "Create PR"
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Automated update to backend: v${{ steps.get-latest.outputs.version }}"
          body: |
            This PR was automatically generated by the GitHub Action `.github/workflows/update-backend.yml`

            It updates the backend version to v${{ steps.get-latest.outputs.version }}. For a full description of the changes, see the backend changelog: [v${{ steps.get-latest.outputs.version }}](https://github.com/sefffal/PairPlots.jl/releases/tag/v${{ steps.get-latest.outputs.version }}).
          delete-branch: true
          commit-message: "Update backend version to v${{ steps.get-latest.outputs.version }}"
          add-paths: |
            pyproject.toml
            pairplots/juliapkg.json
